[package]
name = "redeem_script_codebase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
hex = "0.4.3"
chrono = "0.4.19"
rand = "0.8.5"
rust-crypto = "0.2.36"
