[package]
name = "redeem_script_codebase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
bitcoin = "0.31.1"
hex = "0.4.3"
bitcoin_hashes = "0.10.0"
